from config import *

print("KEY:", AZURE_OPENAI_KEY[:5] if AZURE_OPENAI_KEY else None)
print("ENDPOINT:", AZURE_OPENAI_ENDPOINT)
print("DEPLOYMENT:", AZURE_OPENAI_DEPLOYMENT)
print("EMBEDDING:", AZURE_EMBEDDING_DEPLOYMENT)
print("SEARCH:", SEARCH_ENDPOINT)